#!/bin/bash

WD=`pwd`

cd ../gpg-remailer
    build man || exit 1
cd $WD

yodl2html index.yo || exit 1

scp ../gpg-remailer/tmp/man*/*.html index.html \
    fbb,gpgremailer@web.sourceforge.net:htdocs/

rm index.html

cd ../gpg-remailer
    build distclean
