#!/bin/sh

CWD=`pwd`

if [ $# == 0 ] ; then
    echo first argument must be the file to test, in $CWD
    echo the second arg is optional and is the part to run: 
    echo org, dec, doc, enc. 
    echo Mail is not sent
    exit 1
fi

if [ $# == 2 ] ; then
    STEP="--step $2"
fi

tmp/bin/remailer --relax -d -l remailer.log -L 0 --no-mail -n 1 ${STEP} \
        $CWD/remailer.rc < $CWD/$1
